version: "2"
exclude_patterns:
  ############################################
  ## Code Climate's default exclude patterns
  ############################################
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  ############################################

  ############################################
  ## Additional exclude patterns
  - src/assets
  ############################################
