name: Release

on:
  push:
    branches:
      - github-packages

concurrency:
  group: ${{ github.ref }}-release

permissions:
  # actions: read|write|none
  # checks: read|write|none
  contents: write
  # deployments: read|write|none
  issues: write
  packages: write
  pull-requests: write
  # repository-projects: write
  # security-events: read|write|none
  # statuses: read|write|none

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-release-${{ hashFiles('package-lock.json') }}
      - name: install
        run: |
          if [ ! -d "node_modules" ]; then # If we don't have any node_modules (CircleCI cache miss scenario), run yarn install --frozen-lockfile.  Otherwise, we're all set, do nothing.
            npm ci
          fi
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
